In [0]:
import torch

In [2]:
torch.__version__

'1.4.0'

In [0]:
import numpy as np

In [4]:
np.__version__

'1.17.5'

# **TORCH TENSOR**

In [5]:
A = torch.tensor(2)
A

tensor(2)

In [6]:
A = torch.tensor([1, 2, 3])
A

tensor([1, 2, 3])

In [7]:
A = torch.tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8]])
print(A)
print(A.dim())
print(A.shape)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
2
torch.Size([2, 4])


In [8]:
A = torch.tensor([[[1, 2, 3, 4],
                  [5, 6, 7, 8]],
                  [[1, 2, 3, 4],
                  [5, 6, 7, 8]],
                 ])
print(A)
print(A.dim())
print(A.size())
print(A.shape)

tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[1, 2, 3, 4],
         [5, 6, 7, 8]]])
3
torch.Size([2, 2, 4])
torch.Size([2, 2, 4])


In [9]:
A = torch.tensor(np.random.randn(3, 4))
A

tensor([[ 0.9231, -0.0142,  0.6888, -1.5399],
        [ 0.5678,  1.1876,  0.5377, -0.6705],
        [-0.5372,  0.5797,  0.5478, -0.7667]], dtype=torch.float64)

In [10]:
A = torch.tensor(range(1, 11))
A

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
A = torch.zeros(2, 3, dtype=torch.long)
A

tensor([[0, 0, 0],
        [0, 0, 0]])

In [12]:
A = torch.zeros(2, 3)
A

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
A = torch.ones(2, 3)
A

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
A = torch.eye(3, dtype=torch.long)
A

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [15]:
A = torch.eye(2, 3, dtype=torch.long)
A

tensor([[1, 0, 0],
        [0, 1, 0]])

In [16]:
A = torch.rand(2, 3)
A

tensor([[0.6299, 0.7746, 0.7678],
        [0.9753, 0.7452, 0.3094]])

In [17]:
A = torch.randn(2, 3)
A

tensor([[ 2.2276,  0.9611, -0.7620],
        [ 0.1503,  0.5477,  0.5590]])

In [18]:
A = torch.randint(7, 10, (2, 3))
A

tensor([[7, 9, 8],
        [9, 8, 8]])

In [19]:
B = torch.ones_like(A)
B

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
A = torch.linspace(1, 10, 4)
A

tensor([ 1.,  4.,  7., 10.])

In [21]:
A = torch.linspace(1, 10, 10)
A

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
A = torch.randn(2, 3, dtype = torch.float32)
print(type(A))
print(A.type())
print(A.size())
print(A.dim())
print(A.shape)

<class 'torch.Tensor'>
torch.FloatTensor
torch.Size([2, 3])
2
torch.Size([2, 3])


In [23]:
A = torch.eye(5)
A

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [24]:
A[3:]

tensor([[0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [25]:
A[:3]

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [26]:
A[[0, 1, 3],
  [0, 2, 3]]

tensor([1., 0., 1.])

In [27]:
A = torch.ones(5, 4)
A

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
A[:2] = 0
A

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
A.t()

tensor([[0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.]])

In [30]:
A.transpose(1, 0)

tensor([[0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.]])

In [31]:
A.transpose(0, 1)

tensor([[0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.]])

In [32]:
A

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
A.transpose_(1, 0)                              # using "_" is equivalent as "inplace = True"

tensor([[0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.]])

In [34]:
A                                               # now original A is replaced

tensor([[0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.]])

In [35]:
A = torch.ones(2, 3)
A

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [36]:
B = torch.ones(2, 3)
B

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [37]:
torch.add(A, B)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [38]:
A

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [39]:
A.add_(B)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [40]:
A

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [41]:
A = torch.tensor([1.0, 2.0])
A

tensor([1., 2.])

In [42]:
out = A.pow(2)
out

tensor([1., 4.])

In [43]:
out = A.pow(2).sum()
out

tensor(5.)

In [0]:
A = torch.eye(5, 5)
B = torch.ones(5, 5)

In [45]:
A

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [46]:
B

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [47]:
print(A * B)                                     # element-wise product

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [48]:
A = torch.eye(5, 5)
B = torch.ones(5, 5)
C = A * B
C.rot90()                                        # torch.rot90()

tensor([[0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.]])

# **CUDA TENSOR**

PyTorch provides the option to easily manipulate tensors in addition to moving them from gpu and cpu, which allows for ease of training and controlling which parts should be commited to the gpu or the cpu. This gives the control/flexibility to the programmer to design the models for different scenarios with different compute resources.

In [49]:
# check if cuda is available in your computer
print("---------------------------------------------------")
print("Cuda status:", torch.cuda.is_available())

device_0 = torch.device("cuda")
device_1 = torch.device("cpu")

print("---------------------------------------------------")

---------------------------------------------------
Cuda status: True
---------------------------------------------------


In [52]:
x = torch.rand(2, 3)
y = torch.ones_like(x, device=device_0)
z = torch.zeros_like(x, device=device_1)
print("---------------------------------------------------")
print("Tensor x is stored in: ", x.device)
print(x)
print("Tensor y is stored in: ", y.device)
print(y)
print("---------------------------------------------------")
print("Tensor z is stored in: ", z.device)
print(z)

---------------------------------------------------
Tensor x is stored in:  cpu
tensor([[0.3883, 0.4853, 0.1978],
        [0.3483, 0.8387, 0.6902]])
Tensor y is stored in:  cuda:0
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
---------------------------------------------------
Tensor z is stored in:  cpu
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [53]:
# check if tensor stored in GPU

print(x.is_cuda)
print(y.is_cuda)
print(z.is_cuda)

False
True
False


In [60]:
%%time
a = torch.rand(1000, 1000)
b = torch.rand(1000, 1000)

a.matmul(b)

CPU times: user 35.4 ms, sys: 470 µs, total: 35.9 ms
Wall time: 41 ms


In [61]:
%%time
a = torch.rand(1000, 1000).cuda()
b = torch.rand(1000, 1000).cuda()

a.matmul(b)

CPU times: user 14.7 ms, sys: 1.56 ms, total: 16.3 ms
Wall time: 17.3 ms


### **Pipeline of Tensor Operations**
With PyTorch everything is a **chain** of operations and the high-level APIs offer all the necessary functionalities to achieve this. Below, we will explore a simple approach to chaining tensor operations. In other words, we are designing a graph or a flow of operations that are chained together, designed to output something. This is essential for training neural networks. This is why neural networks are sometimes called **computation graphs**, because they are simply a chain of operations.

In [0]:
import torch.nn as nn

class Chain(nn.Module):
  def __init__(self, ):
    super(Chain, self).__init__()
    
  def forward(self, x):
    print("---------------------------------------------------")
    print("X:")
    print(x)
    print("---------------------------------------------------")
    print("X powered by 2:")
    print(x.pow(2))
    print("mean(X): ")
    out = x.mean()
    return out

In [63]:
x =  torch.rand((4,5), dtype=torch.float64)
chain = Chain()
mean_x = chain(x)
print(mean_x)

---------------------------------------------------
X:
tensor([[0.1667, 0.7636, 0.6157, 0.2144, 0.0631],
        [0.1726, 0.9320, 0.1427, 0.1462, 0.4803],
        [0.3450, 0.6269, 0.9312, 0.3114, 0.9353],
        [0.4146, 0.7578, 0.1910, 0.9535, 0.9061]], dtype=torch.float64)
---------------------------------------------------
X powered by 2:
tensor([[0.0278, 0.5831, 0.3791, 0.0460, 0.0040],
        [0.0298, 0.8687, 0.0204, 0.0214, 0.2307],
        [0.1190, 0.3929, 0.8670, 0.0970, 0.8748],
        [0.1719, 0.5743, 0.0365, 0.9091, 0.8210]], dtype=torch.float64)
mean(X): 
tensor(0.5035, dtype=torch.float64)


In [64]:
y = torch.eye(5,5)
print(torch.mean(y))
chain_2 = Chain()
mean_y = chain_2(y)
print(mean_y)

tensor(0.2000)
---------------------------------------------------
X:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
---------------------------------------------------
X powered by 2:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
mean(X): 
tensor(0.2000)
