In [0]:
import torch

In [0]:
torch.__version__

'1.5.0+cu101'

In [0]:
import numpy as np
import pandas as pd

In [0]:
np.__version__

'1.18.4'

In [0]:
pd.__version__

'1.0.3'

# **TORCH TENSORs**

In [0]:
A = torch.tensor(2)
A

tensor(2)

In [0]:
A = torch.tensor([1, 2, 3])
A

tensor([1, 2, 3])

In [0]:
A = torch.tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8]])
print(A)
print(A.dim())
print(A.shape)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
2
torch.Size([2, 4])


In [0]:
A = torch.tensor([[[1, 2, 3, 4],
                  [5, 6, 7, 8]],
                  [[1, 2, 3, 4],
                  [5, 6, 7, 8]],
                 ])
print(A)
print(A.dim())
print(A.size())
print(A.shape)

tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[1, 2, 3, 4],
         [5, 6, 7, 8]]])
3
torch.Size([2, 2, 4])
torch.Size([2, 2, 4])


In [0]:
A = torch.tensor(np.random.randn(3, 4))                                # build tensors from NumPy array 
A

tensor([[-0.6524, -0.3294,  0.0683,  0.4443],
        [-0.7984, -0.2185,  1.8715,  0.0384],
        [-1.3385,  0.5763, -0.5874,  0.3036]], dtype=torch.float64)

In [0]:
A = torch.tensor(range(1, 11))                                         # range( ) function
A

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Comparison table b/w NumPy arrays & Torch tensors:**

In [0]:
index = ['numpy.uint8', 'numpy.int16', 'numpy.int32',
         'numpy.int', 'numpy.int64', 'numpy.float32',
         'numpy.float', 'numpy.float64']

values = ['torch.ByteTensor', 'torch.ShortTensor', 'torch.IntTensor',
          'torch.LongTensor', 'torch.LongTensor', 'torch.FloatTensor',
          'torch.DoubleTensor', 'torch.DoubleTensor']

In [0]:
NumPy_PyTorch = pd.DataFrame(values, index = index, columns = ['Tensor data type'])

NumPy_PyTorch

Tensor data type
numpy.uint8      torch.ByteTensor
numpy.int16     torch.ShortTensor
numpy.int32       torch.IntTensor
numpy.int        torch.LongTensor
numpy.int64      torch.LongTensor
numpy.float32   torch.FloatTensor
numpy.float    torch.DoubleTensor
numpy.float64  torch.DoubleTensor

In [0]:
A = torch.zeros(2, 3, dtype=torch.long)
A

tensor([[0, 0, 0],
        [0, 0, 0]])

In [0]:
A = torch.zeros(2, 3)
A

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [0]:
A = torch.ones(2, 3)
A

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [0]:
A = torch.eye(3, dtype=torch.long)
A

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [0]:
A = torch.eye(2, 3, dtype=torch.short)
A

tensor([[1, 0, 0],
        [0, 1, 0]], dtype=torch.int16)

In [0]:
A = torch.rand(2, 3)
A

tensor([[0.9841, 0.3227, 0.2623],
        [0.3840, 0.0031, 0.1386]])

In [0]:
A = torch.randn(2, 3)
A

tensor([[-1.0237,  0.2839, -0.5131],
        [-0.9632, -2.7408,  1.1649]])

In [0]:
A = torch.randint(7, 10, (2, 3))
A

tensor([[7, 9, 8],
        [8, 7, 8]])

In [0]:
B = torch.ones_like(A)                                   # build tensors maintain previous tensor's properties such as dim
B

tensor([[1, 1, 1],
        [1, 1, 1]])

In [0]:
A = torch.linspace(1, 10, 4)                             # linspace( )
A

tensor([ 1.,  4.,  7., 10.])

In [0]:
A = torch.linspace(1, 10, 10)
A

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
A = torch.randn(2, 3, dtype = torch.float32)
print(type(A))
print(A.type())
print(A.size())
print(A.dim())
print(A.shape)

<class 'torch.Tensor'>
torch.FloatTensor
torch.Size([2, 3])
2
torch.Size([2, 3])


In [0]:
A = torch.eye(5)
A

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [0]:
A[3:]

tensor([[0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [0]:
A[:3]

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [0]:
A[[0, 1, 3],                                                 # 1st[] be the row number and 2nd[] be the column number for selecting specific elements 
  [0, 2, 3]]

tensor([1., 0., 1.])

In [0]:
A = torch.ones(5, 4)
A

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [0]:
A[:2] = 0
A

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [0]:
A.t()

tensor([[0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.]])

In [0]:
A.transpose(1, 0)

tensor([[0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.]])

In [0]:
A.transpose(0, 1)

tensor([[0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.]])

In [0]:
A

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [0]:
A.transpose_(1, 0)                              # using "_" is equivalent as "inplace = True"

tensor([[0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.]])

In [0]:
A                                               # now original A is replaced

tensor([[0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 1., 1., 1.]])

In [0]:
A = torch.ones(2, 3)
A

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [0]:
B = torch.ones(2, 3)
B

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [0]:
torch.add(A, B)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [0]:
A

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [0]:
A.add_(B)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [0]:
A

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [0]:
A = torch.tensor([1.0, 2.0])
A

tensor([1., 2.])

In [0]:
out = A.pow(2)
out

tensor([1., 4.])

In [0]:
out = A.pow(2).sum()
out

tensor(5.)

In [0]:
A = torch.eye(5, 5)
B = torch.ones(5, 5)

In [0]:
A

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [0]:
B

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [0]:
print(A * B)                                     # element-wise product

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [0]:
A = torch.eye(5, 5)
B = torch.ones(5, 5)
C = A * B
C.rot90()                                        # torch.rot90()

tensor([[0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.]])

# **CUDA TENSORs**

PyTorch provides the option to easily manipulate tensors in addition to moving them from gpu and cpu, which allows for ease of training and controlling which parts should be commited to the gpu or the cpu. This gives the control/flexibility to the programmer to design the models for different scenarios with different compute resources.

In [0]:
# check if cuda is available in your computer
print("---------------------------------------------------")
print("Cuda status:", torch.cuda.is_available())

device_0 = torch.device("cuda")
device_1 = torch.device("cpu")

print("---------------------------------------------------")

---------------------------------------------------
Cuda status: True
---------------------------------------------------


In [0]:
x = torch.rand(2, 3)
y = torch.ones_like(x, device=device_0)
z = torch.zeros_like(x, device=device_1)
print("---------------------------------------------------")
print("Tensor x is stored in: ", x.device)
print(x)
print("Tensor y is stored in: ", y.device)
print(y)
print("---------------------------------------------------")
print("Tensor z is stored in: ", z.device)
print(z)

---------------------------------------------------
Tensor x is stored in:  cpu
tensor([[0.7069, 0.1329, 0.1839],
        [0.8886, 0.4776, 0.5873]])
Tensor y is stored in:  cuda:0
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
---------------------------------------------------
Tensor z is stored in:  cpu
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [0]:
# check if tensor stored in GPU

print(x.is_cuda)
print(y.is_cuda)
print(z.is_cuda)

False
True
False


In [0]:
%%time

a = torch.rand(1000, 1000)
b = torch.rand(1000, 1000)

a.matmul(b)

CPU times: user 47 ms, sys: 0 ns, total: 47 ms
Wall time: 47.8 ms


**GPU computation is way faster than CPU if tensor is huge:**

In [0]:
%%time

a = torch.rand(1000, 1000).cuda()
b = torch.rand(1000, 1000).cuda()

a.matmul(b)

CPU times: user 22.4 ms, sys: 0 ns, total: 22.4 ms
Wall time: 24.1 ms


### **Pipeline of Tensor Operations**
With PyTorch everything is a **chain** of operations and the high-level APIs offer all the necessary functionalities to achieve this. Below, we will explore a simple approach to chaining tensor operations. In other words, we are designing a graph or a flow of operations that are chained together, designed to output something. This is essential for training neural networks. This is why neural networks are sometimes called **computation graphs**, because they are simply a chain of operations.

In [0]:
import torch.nn as nn

class Chain(nn.Module):
  def __init__(self, ):
    super(Chain, self).__init__()
    
  def forward(self, x):
    print("---------------------------------------------------")
    print("X:")
    print(x)
    print("---------------------------------------------------")
    print("X powered by 2:")
    print(x.pow(2))
    print("mean(X): ")
    out = x.mean()
    return out

In [0]:
x =  torch.rand((4,5), dtype=torch.float64)
chain = Chain()
mean_x = chain(x)
print(mean_x)

---------------------------------------------------
X:
tensor([[0.6344, 0.3426, 0.0296, 0.0725, 0.0943],
        [0.2962, 0.6221, 0.5092, 0.2060, 0.6786],
        [0.3925, 0.1269, 0.7806, 0.0953, 0.1974],
        [0.1640, 0.0158, 0.2380, 0.0300, 0.5791]], dtype=torch.float64)
---------------------------------------------------
X powered by 2:
tensor([[4.0244e-01, 1.1736e-01, 8.7661e-04, 5.2505e-03, 8.8983e-03],
        [8.7706e-02, 3.8703e-01, 2.5928e-01, 4.2451e-02, 4.6055e-01],
        [1.5403e-01, 1.6104e-02, 6.0933e-01, 9.0874e-03, 3.8953e-02],
        [2.6897e-02, 2.4871e-04, 5.6627e-02, 8.9706e-04, 3.3536e-01]],
       dtype=torch.float64)
mean(X): 
tensor(0.3052, dtype=torch.float64)


In [0]:
y = torch.eye(5,5)
print(torch.mean(y))
chain_2 = Chain()
mean_y = chain_2(y)
print(mean_y)

tensor(0.2000)
---------------------------------------------------
X:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
---------------------------------------------------
X powered by 2:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
mean(X): 
tensor(0.2000)
