In [87]:
import numpy as np
import pandas as pd
import torch

In [17]:
torch.version.__version__

'1.3.1'

In [18]:
x = [12, 23, 34, 45, 56, 67, 78, 89]

In [19]:
torch.is_tensor(x)

False

In [20]:
torch.is_storage(x)

False

In [21]:
y = torch.randn(1,2,3,4,5)

In [22]:
y

tensor([[[[[-0.7611,  0.6658,  0.7988, -1.2157, -0.2576],
           [-0.9722, -0.0778, -1.1002,  1.4887, -1.3689],
           [-1.6008, -1.4931, -0.1590, -0.4415,  0.2585],
           [-0.4521,  0.1498,  1.1229, -0.3271,  0.1184]],

          [[-0.5979,  2.7634, -0.8247,  1.4445, -0.7798],
           [ 1.3818, -0.3185,  2.0737,  0.6228,  0.9586],
           [-0.0785, -1.6873,  0.2306, -0.2906,  0.4274],
           [-0.8672, -1.0244,  0.0078, -0.6071,  0.3792]],

          [[-0.3099,  0.5614,  0.9924,  0.5982,  1.0007],
           [-0.1218,  0.0303, -0.6100,  0.1875, -0.7134],
           [ 0.5520,  1.1094, -2.9107, -0.6112, -1.3963],
           [-1.5274,  0.8838, -0.5381,  0.5348,  0.7083]]],


         [[[-0.1139, -0.3619,  0.5369, -1.1460, -0.6595],
           [ 0.1596, -0.8848, -1.0703,  1.6707, -0.3640],
           [ 1.7760,  0.8899,  1.7824, -0.5276,  0.0118],
           [ 2.1973, -1.1296, -0.4969, -0.6293, -0.0809]],

          [[ 0.8916,  1.5257,  0.3098, -1.9781, -0.3772],
    

In [23]:
torch.is_tensor(y)

True

In [24]:
torch.is_storage(y)

False

In [25]:
torch.numel(y)                                #      number of all elements in the tensor input 

120

In [26]:
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
torch.numel(torch.zeros(4,4))

16

In [28]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [29]:
torch.eye(4,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]])

In [30]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [32]:
x

[12, 23, 34, 45, 56, 67, 78, 89]

In [33]:
x1 = np.array(x)

In [34]:
x1

array([12, 23, 34, 45, 56, 67, 78, 89])

In [35]:
torch.from_numpy(x1)

tensor([12, 23, 34, 45, 56, 67, 78, 89], dtype=torch.int32)

In [36]:
torch.linspace(2, 10, 25)

tensor([ 2.0000,  2.3333,  2.6667,  3.0000,  3.3333,  3.6667,  4.0000,  4.3333,
         4.6667,  5.0000,  5.3333,  5.6667,  6.0000,  6.3333,  6.6667,  7.0000,
         7.3333,  7.6667,  8.0000,  8.3333,  8.6667,  9.0000,  9.3333,  9.6667,
        10.0000])

In [37]:
torch.logspace(-10, 10, 15)

tensor([1.0000e-10, 2.6827e-09, 7.1969e-08, 1.9307e-06, 5.1795e-05, 1.3895e-03,
        3.7276e-02, 1.0000e+00, 2.6827e+01, 7.1969e+02, 1.9307e+04, 5.1795e+05,
        1.3895e+07, 3.7276e+08, 1.0000e+10])

In [38]:
torch.rand(10)

tensor([0.3475, 0.4249, 0.6468, 0.6320, 0.2447, 0.8919, 0.2901, 0.5113, 0.9052,
        0.3733])

In [39]:
torch.rand(4,5)

tensor([[0.3499, 0.2337, 0.5168, 0.3270, 0.8815],
        [0.5380, 0.4085, 0.8024, 0.3740, 0.2867],
        [0.1676, 0.6020, 0.8583, 0.9360, 0.6579],
        [0.3435, 0.9478, 0.5457, 0.9224, 0.6092]])

In [40]:
torch.randn(10)

tensor([-1.2136,  1.5041, -0.7700, -1.4156, -1.2362, -0.6225,  0.4875,  0.3139,
         0.7573, -1.5470])

In [41]:
torch.randn(4, 5)

tensor([[ 0.0861,  1.9680,  0.9982,  0.4076,  0.1593],
        [-1.5692, -0.9238,  0.8302,  0.6654,  0.0222],
        [ 3.0087, -0.1379, -0.9523, -1.3069, -2.3986],
        [ 0.2350,  0.7274,  0.0649, -0.7296, -0.0495]])

In [42]:
torch.randint(1, 23, (3,2))

tensor([[ 6, 12],
        [11, 18],
        [21, 12]])

In [43]:
torch.arange(10, 40)

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [44]:
torch.arange(10, 40, 2)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [46]:
t = torch.randn(4, 5)

In [49]:
t

tensor([[-1.5196, -1.6831,  0.0069,  0.0667, -0.3583],
        [-0.3532, -0.4341,  0.8361,  0.6803,  0.8713],
        [ 0.0169, -0.5326, -0.9188,  0.0465, -1.4671],
        [ 0.0473,  0.7655,  1.3117, -0.0873,  0.3997]])

In [48]:
t.argmax()

tensor(17)

In [50]:
torch.argmax(t)

tensor(17)

In [51]:
torch.argmax(t, dim = 1)                                #  this is different from NumPy syntax of using "axis"

tensor([3, 4, 3, 2])

In [52]:
torch.argmax(t, dim = 0)

tensor([3, 3, 3, 1, 1])

In [53]:
x = torch.rand(4,5)

In [54]:
x

tensor([[0.3556, 0.9924, 0.9726, 0.2934, 0.4906],
        [0.9037, 0.6322, 0.0945, 0.1381, 0.8130],
        [0.1915, 0.9884, 0.0563, 0.3286, 0.5171],
        [0.1608, 0.7361, 0.1895, 0.4838, 0.8602]])

In [57]:
torch.cat((x,x))

tensor([[0.3556, 0.9924, 0.9726, 0.2934, 0.4906],
        [0.9037, 0.6322, 0.0945, 0.1381, 0.8130],
        [0.1915, 0.9884, 0.0563, 0.3286, 0.5171],
        [0.1608, 0.7361, 0.1895, 0.4838, 0.8602],
        [0.3556, 0.9924, 0.9726, 0.2934, 0.4906],
        [0.9037, 0.6322, 0.0945, 0.1381, 0.8130],
        [0.1915, 0.9884, 0.0563, 0.3286, 0.5171],
        [0.1608, 0.7361, 0.1895, 0.4838, 0.8602]])

In [61]:
torch.cat((x,x)).shape

torch.Size([8, 5])

In [59]:
torch.cat((x,x), dim = 1)                                       #  this is different from Pandas syntax of using "pd.concat"

tensor([[0.3556, 0.9924, 0.9726, 0.2934, 0.4906, 0.3556, 0.9924, 0.9726, 0.2934,
         0.4906],
        [0.9037, 0.6322, 0.0945, 0.1381, 0.8130, 0.9037, 0.6322, 0.0945, 0.1381,
         0.8130],
        [0.1915, 0.9884, 0.0563, 0.3286, 0.5171, 0.1915, 0.9884, 0.0563, 0.3286,
         0.5171],
        [0.1608, 0.7361, 0.1895, 0.4838, 0.8602, 0.1608, 0.7361, 0.1895, 0.4838,
         0.8602]])

In [60]:
torch.cat((x,x), dim = 1).shape

torch.Size([4, 10])

In [62]:
a = torch.randn(4, 4)

In [63]:
a

tensor([[-0.2479,  0.3497, -0.8918, -1.3564],
        [ 0.3325, -0.3572, -0.2585,  0.2370],
        [ 0.6038, -0.7905, -0.5030, -0.4412],
        [ 0.2315, -0.6244,  1.8224, -0.5549]])

In [64]:
torch.chunk(a, 2)

(tensor([[-0.2479,  0.3497, -0.8918, -1.3564],
         [ 0.3325, -0.3572, -0.2585,  0.2370]]),
 tensor([[ 0.6038, -0.7905, -0.5030, -0.4412],
         [ 0.2315, -0.6244,  1.8224, -0.5549]]))

In [65]:
torch.chunk(a, 2, dim = 1)

(tensor([[-0.2479,  0.3497],
         [ 0.3325, -0.3572],
         [ 0.6038, -0.7905],
         [ 0.2315, -0.6244]]), tensor([[-0.8918, -1.3564],
         [-0.2585,  0.2370],
         [-0.5030, -0.4412],
         [ 1.8224, -0.5549]]))

In [68]:
torch.tensor([[11, 12], [23, 24]])                                      #  torch.gather() need more ponderance

tensor([[11, 12],
        [23, 24]])

In [70]:
torch.gather(torch.tensor([[11, 12], [23, 24]]), 
             1,
             torch.LongTensor([[0, 0], [1, 0]])
            )

tensor([[11, 11],
        [24, 23]])

In [71]:
torch.LongTensor([[0, 0], [1, 0]])                                      #  torch.LongTensor() need more ponderance

tensor([[0, 0],
        [1, 0]])

In [72]:
a = torch.randn(4, 4) 

In [73]:
a

tensor([[ 0.2604, -0.5185,  1.3253, -1.5018],
        [-0.3291, -1.1457,  1.1236, -2.2479],
        [-0.1345,  0.9931, -1.6219,  0.6365],
        [ 0.7673, -0.0710,  1.4826, -0.0723]])

In [74]:
indices = torch.LongTensor([0, 2])

In [75]:
torch.index_select(a, 0, indices)

tensor([[ 0.2604, -0.5185,  1.3253, -1.5018],
        [-0.1345,  0.9931, -1.6219,  0.6365]])

In [76]:
torch.index_select(a, 1, indices)

tensor([[ 0.2604,  1.3253],
        [-0.3291,  1.1236],
        [-0.1345, -1.6219],
        [ 0.7673,  1.4826]])

In [77]:
a[:, [0, 2]]

tensor([[ 0.2604,  1.3253],
        [-0.3291,  1.1236],
        [-0.1345, -1.6219],
        [ 0.7673,  1.4826]])

In [79]:
torch.nonzero(torch.tensor([10, 00, 23, 0.0, 2, 0]))

# torch.nonzero() analagous to pd.notnull(), altho not the same, but similar in the concept 

tensor([[0],
        [2],
        [4]])

In [88]:
series = pd.Series([10, 00, 0.0, 2, 0])

In [89]:
series

0    10.0
1     0.0
2     0.0
3     2.0
4     0.0
dtype: float64

In [90]:
pd.notnull(series)

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [93]:
torch.split(torch.tensor([12, 31, 45, 12, 2, 56, 67, 78, 98, 9, 19]), 2)

(tensor([12, 31]),
 tensor([45, 12]),
 tensor([ 2, 56]),
 tensor([67, 78]),
 tensor([98,  9]),
 tensor([19]))

In [94]:
torch.split(torch.tensor([12, 31, 45, 12, 2, 56, 67, 78, 98, 9, 19]), 3)

(tensor([12, 31, 45]),
 tensor([12,  2, 56]),
 tensor([67, 78, 98]),
 tensor([ 9, 19]))

In [95]:
x

tensor([[0.3556, 0.9924, 0.9726, 0.2934, 0.4906],
        [0.9037, 0.6322, 0.0945, 0.1381, 0.8130],
        [0.1915, 0.9884, 0.0563, 0.3286, 0.5171],
        [0.1608, 0.7361, 0.1895, 0.4838, 0.8602]])

In [96]:
x.t()

tensor([[0.3556, 0.9037, 0.1915, 0.1608],
        [0.9924, 0.6322, 0.9884, 0.7361],
        [0.9726, 0.0945, 0.0563, 0.1895],
        [0.2934, 0.1381, 0.3286, 0.4838],
        [0.4906, 0.8130, 0.5171, 0.8602]])

In [98]:
x.transpose(1, 0)

tensor([[0.3556, 0.9037, 0.1915, 0.1608],
        [0.9924, 0.6322, 0.9884, 0.7361],
        [0.9726, 0.0945, 0.0563, 0.1895],
        [0.2934, 0.1381, 0.3286, 0.4838],
        [0.4906, 0.8130, 0.5171, 0.8602]])

In [99]:
x.transpose(0, 1)

tensor([[0.3556, 0.9037, 0.1915, 0.1608],
        [0.9924, 0.6322, 0.9884, 0.7361],
        [0.9726, 0.0945, 0.0563, 0.1895],
        [0.2934, 0.1381, 0.3286, 0.4838],
        [0.4906, 0.8130, 0.5171, 0.8602]])

In [100]:
x

tensor([[0.3556, 0.9924, 0.9726, 0.2934, 0.4906],
        [0.9037, 0.6322, 0.0945, 0.1381, 0.8130],
        [0.1915, 0.9884, 0.0563, 0.3286, 0.5171],
        [0.1608, 0.7361, 0.1895, 0.4838, 0.8602]])

In [101]:
torch.unbind(x, 1)                                         # The unbind function removes a dimension from a tensor

(tensor([0.3556, 0.9037, 0.1915, 0.1608]),
 tensor([0.9924, 0.6322, 0.9884, 0.7361]),
 tensor([0.9726, 0.0945, 0.0563, 0.1895]),
 tensor([0.2934, 0.1381, 0.3286, 0.4838]),
 tensor([0.4906, 0.8130, 0.5171, 0.8602]))

In [102]:
torch.unbind(x, 0)

(tensor([0.3556, 0.9924, 0.9726, 0.2934, 0.4906]),
 tensor([0.9037, 0.6322, 0.0945, 0.1381, 0.8130]),
 tensor([0.1915, 0.9884, 0.0563, 0.3286, 0.5171]),
 tensor([0.1608, 0.7361, 0.1895, 0.4838, 0.8602]))