In [1]:
!nvidia-smi

Mon May  4 03:18:16 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [2]:
import pynvml
pynvml.nvmlInit()
handle = pynvml.nvmlDeviceGetHandleByIndex(0)
device_name = pynvml.nvmlDeviceGetName(handle)
if (device_name != b'Tesla T4') and (device_name != b'Tesla P100-PCIE-16GB'):
  raise Exception("""
    Unfortunately this instance does not have a T4 or P100 GPU.
    
    Please make sure you've configured Colab to request a GPU instance type.
    
    Sometimes Colab allocates a Tesla K80 instead of a T4 or P100. Resetting the instance.
If you get a K80 GPU, try Runtime -> Reset all runtimes...
  """)
else:
  print(f'Yes, you got the right kind of GPU to work and it is a {device_name}.')

Yes, you got the right kind of GPU to work and it is a b'Tesla P100-PCIE-16GB'.


In [0]:
import numpy as np
import pandas as pd
import torch

In [4]:
torch.version.__version__

'1.5.0+cu101'

In [0]:
x = [12, 23, 34, 45, 56, 67, 78, 89]

In [6]:
torch.is_tensor(x)

False

In [7]:
torch.is_storage(x)

False

In [0]:
y = torch.randn(1,2,3,4,5)

In [9]:
y

tensor([[[[[ 0.3697, -1.5643, -0.7758,  0.3289, -0.2209],
           [ 0.5812,  1.6100,  0.8334,  0.0770, -1.1966],
           [-0.2313,  0.6644, -1.3470,  0.3931, -0.3722],
           [ 0.7781, -1.8909, -0.7722, -0.9175, -0.6323]],

          [[-0.6123, -0.9740, -0.1306, -0.2481, -1.0783],
           [ 2.0292,  1.0100,  1.1673, -2.3516, -0.7911],
           [ 0.0341,  0.3652, -0.8468, -0.3294,  0.6155],
           [-1.1752, -0.5011,  0.8020,  0.7978, -0.8876]],

          [[-1.0044, -1.2512, -2.3797,  1.1417, -0.8353],
           [-0.8262,  1.1203, -0.2834,  1.3640,  0.6255],
           [ 0.7191, -0.4728, -0.2336, -0.3742,  0.0595],
           [ 0.9170,  1.5297, -0.4484, -0.5167, -0.1459]]],


         [[[-1.6440,  1.8098, -1.4197, -1.5965, -2.6422],
           [ 0.2586,  0.8746, -0.8601, -1.5066,  1.0861],
           [ 0.1445, -0.2876, -1.3217, -0.9823,  0.5318],
           [ 0.4597,  1.7254, -0.2936, -2.4518,  0.1589]],

          [[ 0.1582,  0.0968,  0.6431,  0.5626, -0.0094],
    

In [10]:
torch.is_tensor(y)

True

In [11]:
torch.is_storage(y)

False

In [12]:
torch.numel(y)                                #      number of all elements in the tensor input 

120

In [13]:
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
torch.numel(torch.zeros(4,4))

16

In [15]:
torch.zeros(4,4).shape

torch.Size([4, 4])

In [16]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [17]:
torch.eye(4,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]])

In [18]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [19]:
x

[12, 23, 34, 45, 56, 67, 78, 89]

In [0]:
x1 = np.array(x)

In [21]:
x1

array([12, 23, 34, 45, 56, 67, 78, 89])

In [22]:
torch.from_numpy(x1)

tensor([12, 23, 34, 45, 56, 67, 78, 89])

In [30]:
torch.linspace(2, 10, 25)

tensor([ 2.0000,  2.3333,  2.6667,  3.0000,  3.3333,  3.6667,  4.0000,  4.3333,
         4.6667,  5.0000,  5.3333,  5.6667,  6.0000,  6.3333,  6.6667,  7.0000,
         7.3333,  7.6667,  8.0000,  8.3333,  8.6667,  9.0000,  9.3333,  9.6667,
        10.0000])

In [29]:
torch.logspace(-10, 10, 15)

tensor([1.0000e-10, 2.6827e-09, 7.1969e-08, 1.9307e-06, 5.1795e-05, 1.3895e-03,
        3.7276e-02, 1.0000e+00, 2.6827e+01, 7.1969e+02, 1.9307e+04, 5.1795e+05,
        1.3895e+07, 3.7276e+08, 1.0000e+10])

In [26]:
torch.rand(10)

tensor([0.9277, 0.2098, 0.5568, 0.5310, 0.9303, 0.3561, 0.8180, 0.3543, 0.7935,
        0.8912])

In [25]:
torch.rand(4,5)

tensor([[0.3741, 0.9537, 0.3732, 0.2762, 0.9783],
        [0.4665, 0.2749, 0.8304, 0.5302, 0.8744],
        [0.0447, 0.8161, 0.4443, 0.3613, 0.3870],
        [0.8508, 0.5872, 0.2210, 0.6544, 0.2762]])

In [24]:
torch.randn(10)

tensor([ 0.8363, -0.4729,  0.9365, -0.0725,  0.3862, -0.6284,  0.7976, -0.4752,
        -0.4415, -0.1003])

In [27]:
torch.randn(4, 5)

tensor([[-0.5513, -1.1527,  2.0239, -0.2701,  0.9900],
        [ 1.0117, -0.0804,  0.6796,  0.5769, -0.0189],
        [-2.3318,  1.1252,  0.7766, -1.4248, -0.3213],
        [-1.3969,  1.2537,  0.0963, -0.3141,  0.6894]])

In [23]:
torch.randint(1, 23, (3,2))

tensor([[14, 18],
        [ 7, 11],
        [ 1, 10]])

In [31]:
torch.arange(10, 40)                          # default step == 1

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [28]:
torch.arange(10, 40, 2)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [51]:
torch.randperm(10)                            # random permutation

tensor([5, 2, 4, 1, 9, 3, 8, 7, 6, 0])

In [0]:
t = torch.randn(4, 5)

In [53]:
t

tensor([[-1.2022,  1.1241, -1.3206,  0.6096,  0.5766],
        [-0.2874, -0.2819,  0.2135, -0.4127,  0.5093],
        [-0.3572, -0.0168,  0.4379,  0.1581, -0.9209],
        [ 1.0521,  0.2325, -0.4401,  0.5678, -0.2987]])

In [54]:
t.max()

tensor(1.1241)

In [55]:
torch.argmax(t)

tensor(1)

In [56]:
torch.argmax(t, dim = 1)                                #  this is different from NumPy syntax of using "axis"

tensor([1, 4, 2, 0])

In [57]:
torch.argmax(t, dim = 0)

tensor([3, 0, 2, 0, 0])

In [0]:
x = torch.rand(4,5)

In [59]:
x

tensor([[0.4724, 0.7023, 0.4440, 0.5945, 0.8253],
        [0.1144, 0.8499, 0.5726, 0.1545, 0.1233],
        [0.9133, 0.9968, 0.8209, 0.3488, 0.7747],
        [0.5881, 0.7624, 0.3675, 0.0399, 0.8569]])

In [60]:
x.shape

torch.Size([4, 5])

In [61]:
torch.cat((x,x))

tensor([[0.4724, 0.7023, 0.4440, 0.5945, 0.8253],
        [0.1144, 0.8499, 0.5726, 0.1545, 0.1233],
        [0.9133, 0.9968, 0.8209, 0.3488, 0.7747],
        [0.5881, 0.7624, 0.3675, 0.0399, 0.8569],
        [0.4724, 0.7023, 0.4440, 0.5945, 0.8253],
        [0.1144, 0.8499, 0.5726, 0.1545, 0.1233],
        [0.9133, 0.9968, 0.8209, 0.3488, 0.7747],
        [0.5881, 0.7624, 0.3675, 0.0399, 0.8569]])

In [62]:
torch.cat((x,x)).shape

torch.Size([8, 5])

In [63]:
torch.cat((x,x,x))

tensor([[0.4724, 0.7023, 0.4440, 0.5945, 0.8253],
        [0.1144, 0.8499, 0.5726, 0.1545, 0.1233],
        [0.9133, 0.9968, 0.8209, 0.3488, 0.7747],
        [0.5881, 0.7624, 0.3675, 0.0399, 0.8569],
        [0.4724, 0.7023, 0.4440, 0.5945, 0.8253],
        [0.1144, 0.8499, 0.5726, 0.1545, 0.1233],
        [0.9133, 0.9968, 0.8209, 0.3488, 0.7747],
        [0.5881, 0.7624, 0.3675, 0.0399, 0.8569],
        [0.4724, 0.7023, 0.4440, 0.5945, 0.8253],
        [0.1144, 0.8499, 0.5726, 0.1545, 0.1233],
        [0.9133, 0.9968, 0.8209, 0.3488, 0.7747],
        [0.5881, 0.7624, 0.3675, 0.0399, 0.8569]])

In [64]:
torch.cat((x,x), dim = 1)                                  #  this is different from Pandas syntax of using "pd.concat"

tensor([[0.4724, 0.7023, 0.4440, 0.5945, 0.8253, 0.4724, 0.7023, 0.4440, 0.5945,
         0.8253],
        [0.1144, 0.8499, 0.5726, 0.1545, 0.1233, 0.1144, 0.8499, 0.5726, 0.1545,
         0.1233],
        [0.9133, 0.9968, 0.8209, 0.3488, 0.7747, 0.9133, 0.9968, 0.8209, 0.3488,
         0.7747],
        [0.5881, 0.7624, 0.3675, 0.0399, 0.8569, 0.5881, 0.7624, 0.3675, 0.0399,
         0.8569]])

In [65]:
torch.cat((x,x), dim = 1).shape

torch.Size([4, 10])

In [0]:
a = torch.randn(4, 4)

In [67]:
a

tensor([[ 2.5248,  1.4341,  0.3001,  0.8017],
        [-0.0828, -2.0754, -0.4569,  1.5441],
        [ 0.8952,  0.2963,  1.0984,  0.2713],
        [ 0.0280,  1.5051,  1.6794, -1.7711]])

In [68]:
torch.chunk(a, 2)

(tensor([[ 2.5248,  1.4341,  0.3001,  0.8017],
         [-0.0828, -2.0754, -0.4569,  1.5441]]),
 tensor([[ 0.8952,  0.2963,  1.0984,  0.2713],
         [ 0.0280,  1.5051,  1.6794, -1.7711]]))

In [69]:
torch.chunk(a, 2, dim = 1)

(tensor([[ 2.5248,  1.4341],
         [-0.0828, -2.0754],
         [ 0.8952,  0.2963],
         [ 0.0280,  1.5051]]), tensor([[ 0.3001,  0.8017],
         [-0.4569,  1.5441],
         [ 1.0984,  0.2713],
         [ 1.6794, -1.7711]]))

In [70]:
torch.tensor([[11, 12], [23, 24]])                                      # pretty tricky

tensor([[11, 12],
        [23, 24]])

**The gather function collects elements from a tensor and places it in another tensor using an index argument. The index position is determined by the LongTensor function in PyTorch.**

In [0]:
index = ['numpy.uint8', 'numpy.int16', 'numpy.int32',
         'numpy.int', 'numpy.int64', 'numpy.float32',
         'numpy.float', 'numpy.float64']

values = ['torch.ByteTensor', 'torch.ShortTensor', 'torch.IntTensor',
          'torch.LongTensor', 'torch.LongTensor', 'torch.FloatTensor',
          'torch.DoubleTensor', 'torch.DoubleTensor']

In [72]:
NumPy_PyTorch = pd.DataFrame(values, index = index, columns = ['Tensor data type'])

NumPy_PyTorch

Tensor data type
numpy.uint8      torch.ByteTensor
numpy.int16     torch.ShortTensor
numpy.int32       torch.IntTensor
numpy.int        torch.LongTensor
numpy.int64      torch.LongTensor
numpy.float32   torch.FloatTensor
numpy.float    torch.DoubleTensor
numpy.float64  torch.DoubleTensor

In [73]:
torch.tensor([[11, 12], [23, 24]])

tensor([[11, 12],
        [23, 24]])

In [74]:
torch.LongTensor([[0, 0], [1, 0]])

tensor([[0, 0],
        [1, 0]])

https://blog.csdn.net/edogawachia/article/details/80515038

gather在one-hot为输出的多分类问题中，可以把最大值坐标作为index传进去，然后提取到每一行的正确预测结果，这也是gather可能的一个应用

In [75]:
torch.gather(torch.tensor([[11, 12], [23, 24]]), 
             1,
             torch.LongTensor([[0, 0], [1, 0]])
            )

tensor([[11, 11],
        [24, 23]])

**index_select function fetch elements as somewhat gather does**

In [0]:
a = torch.randn(4, 4) 

In [77]:
a

tensor([[-0.7087,  2.3358, -1.3644, -0.2826],
        [-0.1743,  0.3275, -1.1040, -0.3906],
        [ 0.5691,  0.6367, -0.4238, -0.0608],
        [-0.8128, -1.8839, -0.3759,  0.6366]])

In [0]:
indices = torch.LongTensor([0, 2])

In [79]:
torch.index_select(a, 0, indices)

tensor([[-0.7087,  2.3358, -1.3644, -0.2826],
        [ 0.5691,  0.6367, -0.4238, -0.0608]])

In [80]:
torch.index_select(a, 1, indices)

tensor([[-0.7087, -1.3644],
        [-0.1743, -1.1040],
        [ 0.5691, -0.4238],
        [-0.8128, -0.3759]])

In [81]:
a[:, [0, 2]]

tensor([[-0.7087, -1.3644],
        [-0.1743, -1.1040],
        [ 0.5691, -0.4238],
        [-0.8128, -0.3759]])

In [82]:
torch.nonzero(torch.tensor([10, 00, 23, 0.0, 2, 0]))

# torch.nonzero(), a parallel to np.nonzero(); analagous to pd.notnull(), altho not the same, but similar in the concept

tensor([[0],
        [2],
        [4]])

In [0]:
series = pd.Series([10, 00, 0.0, 2, 0])

In [84]:
series

0    10.0
1     0.0
2     0.0
3     2.0
4     0.0
dtype: float64

In [85]:
np.where(series.notnull())

(array([0, 1, 2, 3, 4]),)

In [86]:
torch.split(torch.tensor([12, 31, 45, 12, 2, 56, 67, 78, 98, 9, 19]), 2)          # so the 2nd arg is for the size of each unit tensor 

(tensor([12, 31]),
 tensor([45, 12]),
 tensor([ 2, 56]),
 tensor([67, 78]),
 tensor([98,  9]),
 tensor([19]))

In [87]:
torch.split(torch.tensor([12, 31, 45, 12, 2, 56, 67, 78, 98, 9, 19]), 3)         # can be applied on un-even data 

(tensor([12, 31, 45]),
 tensor([12,  2, 56]),
 tensor([67, 78, 98]),
 tensor([ 9, 19]))

In [88]:
x

tensor([[0.4724, 0.7023, 0.4440, 0.5945, 0.8253],
        [0.1144, 0.8499, 0.5726, 0.1545, 0.1233],
        [0.9133, 0.9968, 0.8209, 0.3488, 0.7747],
        [0.5881, 0.7624, 0.3675, 0.0399, 0.8569]])

In [89]:
x.t()

tensor([[0.4724, 0.1144, 0.9133, 0.5881],
        [0.7023, 0.8499, 0.9968, 0.7624],
        [0.4440, 0.5726, 0.8209, 0.3675],
        [0.5945, 0.1545, 0.3488, 0.0399],
        [0.8253, 0.1233, 0.7747, 0.8569]])

In [90]:
x.transpose(1, 0)

tensor([[0.4724, 0.1144, 0.9133, 0.5881],
        [0.7023, 0.8499, 0.9968, 0.7624],
        [0.4440, 0.5726, 0.8209, 0.3675],
        [0.5945, 0.1545, 0.3488, 0.0399],
        [0.8253, 0.1233, 0.7747, 0.8569]])

In [91]:
x.transpose(0, 1)

tensor([[0.4724, 0.1144, 0.9133, 0.5881],
        [0.7023, 0.8499, 0.9968, 0.7624],
        [0.4440, 0.5726, 0.8209, 0.3675],
        [0.5945, 0.1545, 0.3488, 0.0399],
        [0.8253, 0.1233, 0.7747, 0.8569]])

In [92]:
x

tensor([[0.4724, 0.7023, 0.4440, 0.5945, 0.8253],
        [0.1144, 0.8499, 0.5726, 0.1545, 0.1233],
        [0.9133, 0.9968, 0.8209, 0.3488, 0.7747],
        [0.5881, 0.7624, 0.3675, 0.0399, 0.8569]])

In [93]:
torch.unbind(x, 1)                                         # The unbind function removes a dimension from a tensor

(tensor([0.4724, 0.1144, 0.9133, 0.5881]),
 tensor([0.7023, 0.8499, 0.9968, 0.7624]),
 tensor([0.4440, 0.5726, 0.8209, 0.3675]),
 tensor([0.5945, 0.1545, 0.3488, 0.0399]),
 tensor([0.8253, 0.1233, 0.7747, 0.8569]))

In [94]:
torch.unbind(x, 0)

(tensor([0.4724, 0.7023, 0.4440, 0.5945, 0.8253]),
 tensor([0.1144, 0.8499, 0.5726, 0.1545, 0.1233]),
 tensor([0.9133, 0.9968, 0.8209, 0.3488, 0.7747]),
 tensor([0.5881, 0.7624, 0.3675, 0.0399, 0.8569]))