In [2]:
import numpy as np
import pandas as pd
import torch

In [5]:
x = torch.randn(4, 5)

In [6]:
x

tensor([[-0.0780,  0.6253,  0.1402, -0.9923, -0.0975],
        [-0.9456,  1.5767,  0.0719, -0.5269,  0.5385],
        [-0.1604,  0.4347, -1.0990,  0.1995, -0.7523],
        [ 0.3331,  0.5364, -0.2680,  0.9370,  0.0529]])

In [7]:
torch.add(x, 20)

tensor([[19.9220, 20.6253, 20.1402, 19.0077, 19.9025],
        [19.0544, 21.5767, 20.0719, 19.4731, 20.5385],
        [19.8396, 20.4347, 18.9010, 20.1995, 19.2477],
        [20.3331, 20.5364, 19.7320, 20.9370, 20.0529]])

In [11]:
torch.mul(x, 10000)

tensor([[  -779.5810,   6252.6357,   1401.6581,  -9922.9434,   -975.3857],
        [ -9455.7402,  15767.2822,    718.6866,  -5268.5312,   5384.6260],
        [ -1604.0045,   4346.5879, -10989.8994,   1994.8436,  -7523.0386],
        [  3331.2585,   5363.7153,  -2680.3748,   9369.9268,    528.8421]])

In [14]:
intercept = torch.randn(1)

In [15]:
intercept

tensor([-1.3067])

In [16]:
x = torch.randn(2,2)

In [17]:
x

tensor([[ 0.2704, -0.4490],
        [-2.6438, -0.7910]])

In [18]:
beta = 0.74567

In [19]:
torch.add(intercept, torch.mul(x, beta))

tensor([[-1.1051, -1.6415],
        [-3.2781, -1.8966]])

In [20]:
torch.add(torch.mul(intercept,beta), torch.mul(x, beta))

tensor([[-0.7728, -1.3092],
        [-2.9458, -1.5643]])

In [23]:
torch.manual_seed(1234)
torch.randn(5, 5)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539],
        [ 0.6684, -0.0597, -0.4675, -0.2153, -0.7141],
        [-1.0831, -0.5547,  0.9717, -0.5150,  1.4255],
        [ 0.7987, -1.4949,  1.4778, -0.1696, -0.9919],
        [-1.4569,  0.2563, -0.4030,  0.4195,  0.9380]])

In [24]:
torch.manual_seed(1234)
torch.randn(5, 5)
torch.ceil(torch.randn(5, 5))

tensor([[ 1.,  1.,  2., -0.,  1.],
        [ 1., -0.,  2., -0.,  1.],
        [-0.,  1., -1.,  1.,  1.],
        [-0., -0., -1.,  1.,  1.],
        [-0., -0.,  1.,  1., -2.]])

In [25]:
torch.manual_seed(1234)
torch.randn(5, 5)
torch.floor(torch.randn(5, 5))

tensor([[ 0.,  0.,  1., -1.,  0.],
        [ 0., -1.,  1., -1.,  0.],
        [-1.,  0., -2.,  0.,  0.],
        [-1., -1., -2.,  0.,  0.],
        [-1., -1.,  0.,  0., -3.]])

In [26]:
torch.manual_seed(1234)
torch.randn(5, 5)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539],
        [ 0.6684, -0.0597, -0.4675, -0.2153, -0.7141],
        [-1.0831, -0.5547,  0.9717, -0.5150,  1.4255],
        [ 0.7987, -1.4949,  1.4778, -0.1696, -0.9919],
        [-1.4569,  0.2563, -0.4030,  0.4195,  0.9380]])

In [30]:
torch.manual_seed(1234)
torch.floor(torch.randn(5, 5))

tensor([[-1., -1.,  0., -1.,  0.],
        [ 0., -1., -1., -1., -1.],
        [-2., -1.,  0., -1.,  1.],
        [ 0., -2.,  1., -1., -1.],
        [-2.,  0., -1.,  0.,  0.]])

In [31]:
torch.manual_seed(1234)
torch.randn(5, 5)
torch.clamp(torch.floor(torch.randn(5, 5)), min = -0.3, max = 0.4)

tensor([[ 0.0000,  0.0000,  0.4000, -0.3000,  0.0000],
        [ 0.0000, -0.3000,  0.4000, -0.3000,  0.0000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000],
        [-0.3000, -0.3000, -0.3000,  0.0000,  0.0000],
        [-0.3000, -0.3000,  0.0000,  0.0000, -0.3000]])

In [28]:
torch.manual_seed(1234)
torch.randn(5, 5)
torch.clamp(torch.floor(torch.randn(5, 5)), min = -0.3)

tensor([[ 0.0000,  0.0000,  1.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000,  1.0000, -0.3000,  0.0000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000],
        [-0.3000, -0.3000, -0.3000,  0.0000,  0.0000],
        [-0.3000, -0.3000,  0.0000,  0.0000, -0.3000]])

In [29]:
torch.manual_seed(1234)
torch.randn(5, 5)
torch.clamp(torch.floor(torch.randn(5, 5)), max = 0.4)

tensor([[ 0.0000,  0.0000,  0.4000, -1.0000,  0.0000],
        [ 0.0000, -1.0000,  0.4000, -1.0000,  0.0000],
        [-1.0000,  0.0000, -2.0000,  0.0000,  0.0000],
        [-1.0000, -1.0000, -2.0000,  0.0000,  0.0000],
        [-1.0000, -1.0000,  0.0000,  0.0000, -3.0000]])

In [32]:
x

tensor([[ 0.2704, -0.4490],
        [-2.6438, -0.7910]])

In [33]:
torch.exp(x)

tensor([[1.3105, 0.6383],
        [0.0711, 0.4534]])

In [34]:
np.exp(x)

tensor([[1.3105, 0.6383],
        [0.0711, 0.4534]])

In [35]:
torch.add(x, 10)

tensor([[10.2704,  9.5510],
        [ 7.3562,  9.2090]])

In [37]:
torch.frac(torch.add(x, 10))

tensor([[0.2704, 0.5510],
        [0.3562, 0.2090]])

In [38]:
x

tensor([[ 0.2704, -0.4490],
        [-2.6438, -0.7910]])

In [39]:
torch.log(x)

tensor([[-1.3079,     nan],
        [    nan,     nan]])

In [40]:
torch.pow(x, 2)                                   #    power is different from np and Pythonic syntax

tensor([[0.0731, 0.2016],
        [6.9895, 0.6257]])

In [41]:
torch.pow(x, 3)

tensor([[  0.0198,  -0.0905],
        [-18.4784,  -0.4950]])

In [42]:
x

tensor([[ 0.2704, -0.4490],
        [-2.6438, -0.7910]])

In [43]:
torch.sigmoid(x)

tensor([[0.5672, 0.3896],
        [0.0664, 0.3119]])

In [52]:
x

tensor([[ 0.2704, -0.4490],
        [-2.6438, -0.7910]])

In [53]:
torch.sqrt(x)

tensor([[0.5200,    nan],
        [   nan,    nan]])