In [1]:
!nvidia-smi

Mon May  4 03:25:15 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P8    11W /  70W |      0MiB / 15079MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [2]:
import pynvml
pynvml.nvmlInit()
handle = pynvml.nvmlDeviceGetHandleByIndex(0)
device_name = pynvml.nvmlDeviceGetName(handle)
if (device_name != b'Tesla T4') and (device_name != b'Tesla P100-PCIE-16GB'):
  raise Exception("""
    Unfortunately this instance does not have a T4 or P100 GPU.
    
    Please make sure you've configured Colab to request a GPU instance type.
    
    Sometimes Colab allocates a Tesla K80 instead of a T4 or P100. Resetting the instance.
If you get a K80 GPU, try Runtime -> Reset all runtimes...
  """)
else:
  print(f'Yes, you got the right kind of GPU to work and it is a {device_name}.')

Yes, you got the right kind of GPU to work and it is a b'Tesla T4'.


In [0]:
import numpy as np
import pandas as pd
import torch

In [4]:
torch.version.__version__

'1.5.0+cu101'

In [0]:
x = torch.randn(4, 5)

In [6]:
x

tensor([[ 0.7333, -1.9445,  1.6637,  1.3122, -0.9568],
        [ 0.5442, -0.9390,  0.4283,  0.1025, -0.5409],
        [ 0.2499,  1.2315,  1.2553, -0.5111,  1.9191],
        [-0.0226,  2.3526,  0.8215, -0.2813, -1.9022]])

In [7]:
torch.add(x, 20)

tensor([[20.7333, 18.0555, 21.6637, 21.3122, 19.0432],
        [20.5442, 19.0610, 20.4283, 20.1025, 19.4591],
        [20.2499, 21.2315, 21.2553, 19.4889, 21.9191],
        [19.9774, 22.3526, 20.8215, 19.7187, 18.0978]])

In [8]:
torch.mul(x, 10000)

tensor([[  7332.8047, -19445.1367,  16637.4121,  13122.4033,  -9568.3232],
        [  5441.8496,  -9389.5781,   4282.9966,   1025.0168,  -5408.7109],
        [  2499.3215,  12315.3154,  12552.8896,  -5110.5708,  19190.8809],
        [  -225.8898,  23525.5547,   8214.9824,  -2812.8047, -19021.8516]])

In [0]:
intercept = torch.randn(1)

In [10]:
intercept

tensor([-2.0309])

In [0]:
x = torch.randn(2,2)

In [12]:
x

tensor([[ 1.8680, -0.0176],
        [-0.4133,  0.9870]])

In [0]:
beta = torch.tensor([0.789, 1.32])

In [14]:
beta

tensor([0.7890, 1.3200])

In [15]:
torch.mul(x, beta)

tensor([[ 1.4738, -0.0232],
        [-0.3261,  1.3029]])

In [16]:
torch.add(intercept, torch.mul(x, beta))

tensor([[-0.5571, -2.0541],
        [-2.3570, -0.7280]])

In [18]:
- 2.0309 + 1.4738

-0.5570999999999999

In [19]:
torch.manual_seed(1234)
torch.randn(5, 5)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539],
        [ 0.6684, -0.0597, -0.4675, -0.2153, -0.7141],
        [-1.0831, -0.5547,  0.9717, -0.5150,  1.4255],
        [ 0.7987, -1.4949,  1.4778, -0.1696, -0.9919],
        [-1.4569,  0.2563, -0.4030,  0.4195,  0.9380]])

In [20]:
torch.manual_seed(1234)
torch.ceil(torch.randn(5, 5))

tensor([[-0., -0.,  1., -0.,  1.],
        [ 1., -0., -0., -0., -0.],
        [-1., -0.,  1., -0.,  2.],
        [ 1., -1.,  2., -0., -0.],
        [-1.,  1., -0.,  1.,  1.]])

In [21]:
torch.manual_seed(1234)
torch.floor(torch.randn(5, 5))

tensor([[-1., -1.,  0., -1.,  0.],
        [ 0., -1., -1., -1., -1.],
        [-2., -1.,  0., -1.,  1.],
        [ 0., -2.,  1., -1., -1.],
        [-2.,  0., -1.,  0.,  0.]])

In [22]:
torch.manual_seed(1234)
torch.randn(5, 5)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539],
        [ 0.6684, -0.0597, -0.4675, -0.2153, -0.7141],
        [-1.0831, -0.5547,  0.9717, -0.5150,  1.4255],
        [ 0.7987, -1.4949,  1.4778, -0.1696, -0.9919],
        [-1.4569,  0.2563, -0.4030,  0.4195,  0.9380]])

In [23]:
torch.manual_seed(1234)
torch.floor(torch.randn(5, 5))

tensor([[-1., -1.,  0., -1.,  0.],
        [ 0., -1., -1., -1., -1.],
        [-2., -1.,  0., -1.,  1.],
        [ 0., -2.,  1., -1., -1.],
        [-2.,  0., -1.,  0.,  0.]])

In [24]:
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5, 5)), min = -0.3, max = 0.4)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  0.4000],
        [ 0.0000, -0.3000,  0.4000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

Limiting the values of any tensor within a certain range can be done using the minimum and maximum argument and using the clamp function above

In [25]:
torch.manual_seed(1234)                                         # truncate with only lower limit
torch.clamp(torch.floor(torch.randn(5, 5)), min = -0.3)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  1.0000],
        [ 0.0000, -0.3000,  1.0000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [26]:
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5, 5)), max = 0.4)

tensor([[-1.0000, -1.0000,  0.0000, -1.0000,  0.0000],
        [ 0.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-2.0000, -1.0000,  0.0000, -1.0000,  0.4000],
        [ 0.0000, -2.0000,  0.4000, -1.0000, -1.0000],
        [-2.0000,  0.0000, -1.0000,  0.0000,  0.0000]])

In [27]:
x

tensor([[ 1.8680, -0.0176],
        [-0.4133,  0.9870]])

In [40]:
%%time
torch.exp(x)

CPU times: user 260 µs, sys: 0 ns, total: 260 µs
Wall time: 166 µs


tensor([[6.4750, 0.9825],
        [0.6614, 2.6832]])

In [41]:
x_arr = np.array([[1.8680, -0.0176], 
                  [-0.4133,  0.9870]])
x_arr

array([[ 1.868 , -0.0176],
       [-0.4133,  0.987 ]])

In [42]:
%%time
np.exp(x_arr)

CPU times: user 18 µs, sys: 4 µs, total: 22 µs
Wall time: 22.6 µs


array([[6.47533277, 0.98255398],
       [0.66146381, 2.68317287]])

In [43]:
torch.add(x, 10)

tensor([[11.8680,  9.9824],
        [ 9.5867, 10.9870]])

In [44]:
torch.frac(torch.add(x, 10))

tensor([[0.8680, 0.9824],
        [0.5867, 0.9870]])

In [45]:
x

tensor([[ 1.8680, -0.0176],
        [-0.4133,  0.9870]])

In [47]:
torch.log(x)

tensor([[ 0.6248,     nan],
        [    nan, -0.0131]])

In [48]:
torch.pow(x, 2)                                   #    power is different from np and Pythonic syntax

tensor([[3.4893e+00, 3.0992e-04],
        [1.7086e-01, 9.7420e-01]])

In [49]:
torch.pow(x, 3)

tensor([[ 6.5178e+00, -5.4561e-06],
        [-7.0624e-02,  9.6155e-01]])

In [50]:
x

tensor([[ 1.8680, -0.0176],
        [-0.4133,  0.9870]])

In [51]:
torch.sigmoid(x)

tensor([[0.8662, 0.4956],
        [0.3981, 0.7285]])

In [53]:
torch.sqrt(x)

tensor([[1.3667,    nan],
        [   nan, 0.9935]])