In [3]:
import numpy as np
import pandas as pd
import torch

from torch.autograd import Variable
from torch import FloatTensor
from torch.autograd import Variable

In [4]:
torch.version.__version__

'1.3.1'

In [5]:
torch.manual_seed(1234)

torch.randn(4,4)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817],
        [ 0.0539,  0.6684, -0.0597, -0.4675],
        [-0.2153,  0.8840, -0.7584, -0.3689],
        [-0.3424, -1.4020,  0.3206, -1.0219]])

In [6]:
torch.Tensor(4, 4).uniform_(0, 1)                                                              # uniform

tensor([[0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294],
        [0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343]])

In [7]:
torch.bernoulli(torch.Tensor(4, 4).uniform_(0, 1))                                             # bernoulli

tensor([[0., 0., 0., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 1.],
        [0., 0., 0., 0.]])

In [8]:
torch.tensor([10, 10, 13, 10, 34, 45, 65, 67, 87, 89, 87, 34])

tensor([10, 10, 13, 10, 34, 45, 65, 67, 87, 89, 87, 34])

In [9]:
torch.Tensor([10, 10, 13, 10, 34, 45, 65, 67, 87, 89, 87, 34])

tensor([10., 10., 13., 10., 34., 45., 65., 67., 87., 89., 87., 34.])

In [10]:
torch.multinomial(torch.Tensor([10, 10, 13, 10, 34, 45, 65, 67, 87, 89, 87, 34]), 3)     # multinomial & the default is no replacement 

tensor([10,  7,  6])

In [11]:
torch.multinomial(torch.Tensor([10, 10, 13, 10, 34, 45, 65, 67, 87, 89, 87, 34]), 5, replacement = True)      # returns index position of selected tensor

tensor([11,  4,  4,  8,  6])

In [12]:
torch.normal(mean = torch.arange(1., 11.),   
             std = torch.arange(1, 0, -0.1))                              # normal: often used in CNN, RNN, DNN's weights initialization

tensor([-0.0413,  2.0632,  3.4637,  3.9581,  5.1089,  5.6602,  6.8973,  7.4543,
         9.0422, 10.0337])

In [13]:
torch.normal(mean = 0.5,
             std = torch.arange(1., 6.))

tensor([ 1.1638,  2.5794,  6.0301,  3.1352, -0.6746])

In [14]:
torch.normal(mean = 0.5,
             std = torch.arange(0.2, 0.6))

tensor([0.4939])

**a PyTorch variable is a node in a computational graph, which stores data and gradients**

**The partial derivative of the cost func with respect to the weights and bias in a NN model is achieved in PyTorch using autograd module. Variables are specifically designed to hold the changed values while running a backpropagation in a NN model when the parameters changes. The varibale type is just a wrapper around the tensor, it has 3 properties: data, grad and a function.**

In [15]:
from torch.autograd import Variable

In [16]:
Variable(torch.ones(2, 2), requires_grad = True)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [17]:
a, b = 12, 23

In [18]:
x1 = Variable(torch.randn(a, b),
              requires_grad = True)

In [19]:
x1.shape

torch.Size([12, 23])

In [20]:
x2 = Variable(torch.randn(a, b),
              requires_grad = True)

In [21]:
x3 = Variable(torch.randn(a, b),
              requires_grad = True)

In [22]:
x3.shape

torch.Size([12, 23])

In [23]:
c = x1 * x2

In [24]:
c.shape

torch.Size([12, 23])

In [91]:
c

tensor([[-1.4503e+00,  6.8123e-01, -1.7988e+00, -1.7186e-01, -2.6834e-01,
          5.1251e-01,  8.7220e-02, -3.0699e+00, -2.2617e-02, -1.2692e+00,
          1.1181e-02,  2.4111e+00,  8.3959e-01, -3.5590e-01, -1.0206e+00,
          3.6976e-01,  1.6548e-01,  4.1840e-01, -2.7418e+00,  7.2174e-01,
         -8.2861e-01,  3.3090e-01,  4.6830e-02],
        [ 2.4091e+00, -1.5220e+00,  9.5142e-01,  3.0698e-01, -5.6175e-01,
          3.8284e-01,  2.1250e-01,  5.7908e-01,  1.3809e+00, -1.7068e+00,
         -1.2880e-01, -6.9417e-01, -2.4938e+00, -1.6462e+00,  2.9196e-01,
         -2.3689e-01, -1.3695e-01, -1.9273e-01, -2.4722e-01, -5.5201e-01,
         -1.3090e+00, -3.1640e-01,  2.8343e-02],
        [-1.2700e-01,  5.2778e-01,  1.2260e-01,  2.5652e+00,  8.4692e-01,
         -3.0712e-01, -2.0373e-01, -1.3005e-02,  3.7454e-02, -7.2761e-01,
          2.2506e+00,  2.5721e+00, -9.3050e-01, -1.3236e-01, -2.8468e-03,
         -7.9138e-02,  4.4572e-01,  1.0202e-02, -3.7947e-02,  9.3138e-02,
          7.88

In [25]:
d = a + x3

In [93]:
d.shape

torch.Size([4, 3])

In [92]:
d

tensor([[ 1.,  2.,  3.],
        [ 5.,  4.,  2.],
        [ 3.,  5., 67.],
        [34.,  5.,  6.]])

In [27]:
e = torch.sum(d)

In [28]:
e

tensor(3323.9707, grad_fn=<SumBackward0>)

In [29]:
e.backward()

In [30]:
print(e)

tensor(3323.9707, grad_fn=<SumBackward0>)


**Basic statistics**

In [31]:
torch.mean(torch.tensor([10., 10., 13., 10., 34., 45., 65., 67., 87., 89., 87., 34.]))

tensor(45.9167)

In [32]:
torch.mean(torch.Tensor([10, 10, 13, 10, 34, 45, 65, 67, 87, 89, 87, 34]))

tensor(45.9167)

In [33]:
d = torch.Tensor([1, 2, 3, 5, 4, 2, 3, 5, 67, 34, 5, 6]).view(4, 3)                # .view() is analougous to .reshape() in NumPy 

In [34]:
d

tensor([[ 1.,  2.,  3.],
        [ 5.,  4.,  2.],
        [ 3.,  5., 67.],
        [34.,  5.,  6.]])

In [35]:
torch.mean(d)                           # whole data

tensor(11.4167)

In [36]:
torch.mean(d, dim = 0)                

tensor([10.7500,  4.0000, 19.5000])

In [37]:
torch.mean(d, dim = 1)

tensor([ 2.0000,  3.6667, 25.0000, 15.0000])

In [38]:
torch.median(d)

tensor(4.)

In [39]:
torch.median(d, dim = 0)

torch.return_types.median(
values=tensor([3., 4., 3.]),
indices=tensor([2, 1, 0]))

In [40]:
torch.median(d, dim = 1)

torch.return_types.median(
values=tensor([2., 4., 5., 6.]),
indices=tensor([1, 1, 1, 2]))

In [41]:
torch.mode(d)

torch.return_types.mode(
values=tensor([1., 2., 3., 5.]),
indices=tensor([0, 2, 0, 1]))

In [42]:
torch.mode(d, dim = 0)

torch.return_types.mode(
values=tensor([1., 5., 2.]),
indices=tensor([0, 3, 1]))

In [43]:
torch.mode(d, dim = 1)

torch.return_types.mode(
values=tensor([1., 2., 3., 5.]),
indices=tensor([0, 2, 0, 1]))

In [44]:
torch.std(d)

tensor(19.6212)

In [45]:
torch.std(d, dim = 0)

tensor([15.5858,  1.4142, 31.7122])

In [46]:
torch.std(d, dim = 1)

tensor([ 1.0000,  1.5275, 36.3868, 16.4621])

In [47]:
torch.var(d)

tensor(384.9924)

In [48]:
torch.var(d, dim = 0)

tensor([ 242.9167,    2.0000, 1005.6667])

In [49]:
torch.var(d, dim = 1)

tensor([1.0000e+00, 2.3333e+00, 1.3240e+03, 2.7100e+02])

**Gradient computation**

In [82]:
from torch.autograd import Variable

In [83]:
def forward(x):
    return x * w    

In [84]:
def loss(x, y):
    y_pred = forward(x)
    return (y_pred - y) ** 2

In [85]:
x_data = [11.0, 22.0, 33.0]

In [86]:
y_data = [21.0, 14.0, 64.0]

In [87]:
w = Variable(torch.Tensor([1.0]), requires_grad = True)        # any random value

In [88]:
w

tensor([1.], requires_grad=True)

In [89]:
print("predict before training: ", 4, forward(4).data[0])

predict before training:  4 tensor(4.)


In [90]:
for epoch in range(10):
    for x_val, y_val in zip(x_data, y_data):
        los = loss(x_val, y_val)
        los.backward()
        print("\tgrad: ", x_val, y_val, w.grad.data[0])
        w.data = w.data - 0.01 * w.grad.data
        
        w.grad.data.zero_()                  # mannually set graddients to 0 after updating weights
    print('process: ', epoch, los.data[0])   

print('predict after training: ', 4, forward(4).data[0])

	grad:  11.0 21.0 tensor(-220.)
	grad:  22.0 14.0 tensor(2481.6001)
	grad:  33.0 64.0 tensor(-51303.6484)
process:  0 tensor(604238.8125)
	grad:  11.0 21.0 tensor(118461.7578)
	grad:  22.0 14.0 tensor(-671630.6875)
	grad:  33.0 64.0 tensor(13114108.)
process:  1 tensor(3.9481e+10)
	grad:  11.0 21.0 tensor(-30279010.)
	grad:  22.0 14.0 tensor(1.7199e+08)
	grad:  33.0 64.0 tensor(-3.3589e+09)
process:  2 tensor(2.5900e+15)
	grad:  11.0 21.0 tensor(7.7553e+09)
	grad:  22.0 14.0 tensor(-4.4050e+10)
	grad:  33.0 64.0 tensor(8.6030e+11)
process:  3 tensor(1.6991e+20)
	grad:  11.0 21.0 tensor(-1.9863e+12)
	grad:  22.0 14.0 tensor(1.1282e+13)
	grad:  33.0 64.0 tensor(-2.2034e+14)
process:  4 tensor(1.1146e+25)
	grad:  11.0 21.0 tensor(5.0875e+14)
	grad:  22.0 14.0 tensor(-2.8897e+15)
	grad:  33.0 64.0 tensor(5.6436e+16)
process:  5 tensor(7.3118e+29)
	grad:  11.0 21.0 tensor(-1.3030e+17)
	grad:  22.0 14.0 tensor(7.4013e+17)
	grad:  33.0 64.0 tensor(-1.4455e+19)
process:  6 tensor(4.7966e+34)
	

In [94]:
from torch import FloatTensor
from torch.autograd import Variable

In [96]:
a = Variable(FloatTensor([5]))

In [97]:
a

tensor([5.])

In [98]:
weights = [Variable(FloatTensor([i]), requires_grad = True) for i in (12, 53, 91, 123)]

In [99]:
weights

[tensor([12.], requires_grad=True),
 tensor([53.], requires_grad=True),
 tensor([91.], requires_grad=True),
 tensor([123.], requires_grad=True)]

In [100]:
w1, w2, w3, w4 = weights

In [107]:
b = w1 * a
c = w2 * a
d = w3 * b + w4 * c

Loss = (10 -d)
Loss.backward()

for index, weight in enumerate(weights, start = 1):
    gradient, *_ = weight.grad.data
    print(f"Gradient of w{index} w.r.t. Loss is: {gradient}")    

Gradient of w1 w.r.t. Loss is: -910.0
Gradient of w2 w.r.t. Loss is: -1230.0
Gradient of w3 w.r.t. Loss is: -120.0
Gradient of w4 w.r.t. Loss is: -530.0


In [106]:
b, c, d

(tensor([60.], grad_fn=<MulBackward0>),
 tensor([265.], grad_fn=<MulBackward0>),
 tensor([38055.], grad_fn=<AddBackward0>))

**How to compute or perform operations(such as matirx mult) based on variables?**

**Tensors are wrapped within variables, which has 3 properties: grad, volatile and gradients** 

In [108]:
x = Variable(torch.Tensor(4, 4).uniform_(-4, 5))
y = Variable(torch.Tensor(4, 4).uniform_(-3, 2))

In [109]:
x

tensor([[ 1.7392,  0.8415,  0.4775, -1.3920],
        [ 3.2334, -2.2886,  0.4382,  3.4637],
        [-1.8989, -2.5045,  1.6963, -3.2213],
        [-1.3765,  4.4271,  3.0947,  4.5695]])

In [110]:
y

tensor([[-2.8902, -2.8512,  0.1224,  0.3857],
        [-1.9489,  0.4000, -0.0681, -1.5631],
        [ 1.8341,  1.4200,  1.5710, -1.3153],
        [-0.4852, -1.6904,  1.5460,  1.7711]])

In [113]:
z = torch.mm(x, y)                               # .mm( )     matrix mult module 

In [114]:
z

tensor([[ -5.1153,  -1.5909,  -1.2464,  -3.7379],
        [ -5.7615, -15.3671,   6.5947,  10.3821],
        [ 15.0432,  12.2665,  -2.3772,  -4.7539],
        [ -1.1909,   2.3656,  11.4565,  -3.4282]])

**following shows the properties of the variable, which is a wrapper around the tensor:**

In [116]:
z = Variable(torch.Tensor(4, 4).uniform_(-5, 5))
z

tensor([[ 2.7068, -2.3518, -2.9924, -2.2361],
        [-0.7270,  4.2119, -0.3071, -3.6691],
        [-2.8417, -1.1818, -1.4654, -0.4344],
        [-2.0130, -2.3842,  1.3962,  1.4962]])

In [117]:
print('Requires Gradient: ', z.requires_grad)

Requires Gradient:  False


In [118]:
print('Volatile: ',  (z.volatile))

Volatile:  False


D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: volatile was removed (Variable.volatile is always False)
  """Entry point for launching an IPython kernel.


In [119]:
print('Gradients: ', z.grad)

Gradients:  None


In [120]:
z.data

tensor([[ 2.7068, -2.3518, -2.9924, -2.2361],
        [-0.7270,  4.2119, -0.3071, -3.6691],
        [-2.8417, -1.1818, -1.4654, -0.4344],
        [-2.0130, -2.3842,  1.3962,  1.4962]])

**How to compute or perform linear algebraic operations(such as vector * matrix or vec) based on variables?**

In [123]:
mat1 = torch.FloatTensor(4, 4).uniform_(0, 1)
mat1

tensor([[0.2900, 0.6888, 0.3020, 0.5234],
        [0.3969, 0.5127, 0.9079, 0.2978],
        [0.9516, 0.4772, 0.1602, 0.6753],
        [0.5563, 0.9905, 0.8829, 0.0355]])

In [125]:
mat2 = torch.FloatTensor(5, 4).uniform_(0, 1)
mat2

tensor([[0.4608, 0.0832, 0.9002, 0.9188],
        [0.1386, 0.3701, 0.1947, 0.2268],
        [0.9587, 0.2615, 0.7256, 0.7673],
        [0.5667, 0.1863, 0.4642, 0.4016],
        [0.9981, 0.8452, 0.5569, 0.7666]])

In [126]:
mat1 + 10.                              # scalar operation

tensor([[10.2900, 10.6888, 10.3020, 10.5234],
        [10.3969, 10.5127, 10.9079, 10.2978],
        [10.9516, 10.4772, 10.1602, 10.6753],
        [10.5563, 10.9905, 10.8829, 10.0355]])

In [128]:
vec1 = torch.FloatTensor(4).uniform_(0, 1)

In [129]:
vec1

tensor([0.1084, 0.7874, 0.7348, 0.9939])

In [130]:
mat1

tensor([[0.2900, 0.6888, 0.3020, 0.5234],
        [0.3969, 0.5127, 0.9079, 0.2978],
        [0.9516, 0.4772, 0.1602, 0.6753],
        [0.5563, 0.9905, 0.8829, 0.0355]])

In [131]:
mat1 + vec1

tensor([[0.3984, 1.4762, 1.0368, 1.5173],
        [0.5053, 1.3000, 1.6427, 1.2917],
        [1.0600, 1.2645, 0.8949, 1.6692],
        [0.6647, 1.7779, 1.6177, 1.0294]])

In [132]:
mat1 * mat1

tensor([[0.0841, 0.4745, 0.0912, 0.2739],
        [0.1575, 0.2628, 0.8244, 0.0887],
        [0.9055, 0.2277, 0.0257, 0.4560],
        [0.3094, 0.9812, 0.7796, 0.0013]])

In [135]:
mat2_t = mat2.t()

In [136]:
mat2_t

tensor([[0.4608, 0.1386, 0.9587, 0.5667, 0.9981],
        [0.0832, 0.3701, 0.2615, 0.1863, 0.8452],
        [0.9002, 0.1947, 0.7256, 0.4642, 0.5569],
        [0.9188, 0.2268, 0.7673, 0.4016, 0.7666]])

In [137]:
torch.matmul(mat1, mat2_t)

tensor([[0.9438, 0.4726, 1.0790, 0.6431, 1.4411],
        [1.3165, 0.4891, 1.4019, 0.8615, 1.5634],
        [1.2429, 0.4928, 1.6715, 0.9737, 1.9600],
        [1.1662, 0.6237, 1.4603, 0.9239, 1.9113]])

In [138]:
torch.mm(mat1, mat2_t)

tensor([[0.9438, 0.4726, 1.0790, 0.6431, 1.4411],
        [1.3165, 0.4891, 1.4019, 0.8615, 1.5634],
        [1.2429, 0.4928, 1.6715, 0.9737, 1.9600],
        [1.1662, 0.6237, 1.4603, 0.9239, 1.9113]])

**Distribution**

In [139]:
from torch.distributions.bernoulli import Bernoulli

In [140]:
dist = Bernoulli(torch.tensor([0.3, 0.6, 0.9]))

In [141]:
dist

Bernoulli(probs: torch.Size([3]))

In [142]:
dist.sample()                # sample be binary, takes 1 with p and 0 with 1-p 

tensor([0., 1., 0.])

In [143]:
from torch.distributions.beta import Beta                        # for Bayesian inference, ranges in [0, 1]

In [144]:
dist = Beta(torch.tensor([0.5]), torch.tensor([0.5]))

In [145]:
dist

Beta()

In [146]:
dist.sample()

tensor([0.3572])

In [147]:
from torch.distributions.binomial import Binomial

In [148]:
dist = Binomial(100, torch.tensor([0, .2, .8, 1]))      # 100 counts

In [149]:
dist

Binomial(total_count: torch.Size([4]), probs: torch.Size([4]), logits: torch.Size([4]))

In [150]:
dist.sample()

tensor([  0.,  20.,  80., 100.])

In [152]:
from torch.distributions.categorical import Categorical

In [161]:
dist = Categorical(torch.tensor([0.2, .2, .2, .2, .2]))            # 0.2: event prob

In [162]:
dist

Categorical(probs: torch.Size([5]))

In [164]:
dist.sample()

tensor(4)

In [165]:
from torch.distributions.laplace import Laplace     ## AKA double exponential dist, used in speech recognition to understand prior probs

In [166]:
dist = Laplace(torch.tensor([10.0]), torch.tensor([0.99]))

In [167]:
dist

Laplace(loc: tensor([10.]), scale: tensor([0.9900]))

In [168]:
dist.sample()

tensor([8.1093])

In [169]:
from torch.distributions.normal import Normal

In [170]:
dist = Normal(torch.tensor([0.0]), torch.tensor([1.]))

In [171]:
dist

Normal(loc: tensor([0.]), scale: tensor([1.]))

In [172]:
dist.sample()

tensor([-0.4520])