In [53]:
import numpy as np
import pandas as pd
import torch

from torch.autograd import Variable
from torch import FloatTensor
from torch.autograd import Variable

In [2]:
torch.manual_seed(1234)

torch.randn(4,4)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817],
        [ 0.0539,  0.6684, -0.0597, -0.4675],
        [-0.2153,  0.8840, -0.7584, -0.3689],
        [-0.3424, -1.4020,  0.3206, -1.0219]])

In [3]:
torch.Tensor(4, 4).uniform_(0, 1)

tensor([[0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294],
        [0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343]])

In [4]:
torch.bernoulli(torch.Tensor(4, 4).uniform_(0, 1))

tensor([[0., 0., 0., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 1.],
        [0., 0., 0., 0.]])

In [5]:
torch.tensor([10, 10, 13, 10, 34, 45, 65, 67, 87, 89, 87, 34])

tensor([10, 10, 13, 10, 34, 45, 65, 67, 87, 89, 87, 34])

In [6]:
torch.Tensor([10, 10, 13, 10, 34, 45, 65, 67, 87, 89, 87, 34])

tensor([10., 10., 13., 10., 34., 45., 65., 67., 87., 89., 87., 34.])

In [7]:
torch.multinomial(torch.Tensor([10, 10, 13, 10, 34, 45, 65, 67, 87, 89, 87, 34]), 3)

tensor([10,  7,  6])

In [8]:
torch.multinomial(torch.Tensor([10, 10, 13, 10, 34, 45, 65, 67, 87, 89, 87, 34]), 5, replacement = True)

tensor([11,  4,  4,  8,  6])

In [9]:
torch.normal(mean = torch.arange(1., 11.), 
             std = torch.arange(1, 0, -0.1))

tensor([-0.0413,  2.0632,  3.4637,  3.9581,  5.1089,  5.6602,  6.8973,  7.4543,
         9.0422, 10.0337])

In [10]:
torch.normal(mean = 0.5,
             std = torch.arange(1., 6.))

tensor([ 1.1638,  2.5794,  6.0301,  3.1352, -0.6746])

In [11]:
torch.normal(mean = 0.5,
             std = torch.arange(0.2, 0.6))

tensor([0.4939])

In [12]:
from torch.autograd import Variable

In [13]:
Variable(torch.ones(2, 2), requires_grad = True)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [14]:
a, b = 12, 23

In [15]:
x1 = Variable(torch.rand(a, b),
              requires_grad = True)

In [16]:
x2 = Variable(torch.rand(a, b),
              requires_grad = True)

In [17]:
x3 = Variable(torch.rand(a, b),
              requires_grad = True)

In [18]:
c = x1 * x2

In [19]:
c

tensor([[1.9439e-01, 8.3123e-02, 6.1326e-01, 9.0578e-01, 3.2159e-01, 1.8023e-02,
         2.9322e-01, 3.0344e-01, 9.8868e-03, 2.2838e-01, 6.0316e-02, 5.7139e-02,
         2.4851e-01, 2.7720e-02, 5.5285e-02, 4.6781e-02, 5.9956e-01, 2.6667e-01,
         1.6194e-01, 3.6107e-01, 3.3975e-01, 5.9168e-02, 1.8463e-01],
        [8.2431e-01, 3.7642e-01, 1.2974e-01, 2.8487e-01, 2.2833e-01, 1.2991e-02,
         3.1803e-01, 2.6543e-01, 1.8372e-01, 2.8256e-01, 5.9885e-02, 3.2997e-01,
         3.9870e-01, 2.5413e-01, 1.8421e-01, 8.9223e-02, 7.7667e-01, 2.4835e-01,
         2.7827e-01, 1.7042e-01, 7.2741e-02, 2.1541e-01, 5.5924e-01],
        [2.5814e-01, 3.0717e-01, 8.2730e-01, 2.4071e-01, 5.1900e-01, 2.9513e-01,
         3.5017e-02, 5.9113e-03, 3.3227e-02, 1.7768e-02, 5.3346e-03, 2.3609e-01,
         1.9969e-01, 7.4036e-03, 4.6820e-02, 4.5987e-01, 2.3172e-01, 5.8926e-01,
         1.4114e-01, 2.1472e-01, 9.9913e-02, 4.5357e-02, 9.9508e-03],
        [3.5248e-02, 2.0942e-01, 4.1740e-01, 1.4990e-01, 2.67

In [20]:
d = a + x3

In [21]:
d

tensor([[12.6790, 12.6414, 12.9103, 12.6213, 12.7939, 12.1999, 12.8104, 12.5109,
         12.4445, 12.2756, 12.6853, 12.7588, 12.1340, 12.1134, 12.6995, 12.0575,
         12.0297, 12.8617, 12.6591, 12.5385, 12.4971, 12.7077, 12.1429],
        [12.9157, 12.4303, 12.5491, 12.0267, 12.5304, 12.1945, 12.7813, 12.0250,
         12.9507, 12.3828, 12.3294, 12.4968, 12.0913, 12.6613, 12.9078, 12.2900,
         12.3376, 12.0834, 12.6218, 12.8683, 12.9070, 12.6605, 12.7243],
        [12.1330, 12.2989, 12.9879, 12.5074, 12.7034, 12.1295, 12.0874, 12.8947,
         12.2780, 12.2299, 12.4783, 12.4637, 12.7184, 12.8120, 12.9437, 12.3520,
         12.3704, 12.1080, 12.2461, 12.4065, 12.2440, 12.5123, 12.3927],
        [12.7875, 12.0633, 12.4899, 12.3109, 12.5337, 12.2299, 12.0076, 12.4883,
         12.5447, 12.9341, 12.1595, 12.4255, 12.9049, 12.9816, 12.5763, 12.2561,
         12.7949, 12.1379, 12.0809, 12.5429, 12.2080, 12.6596, 12.2835],
        [12.1386, 12.3173, 12.1742, 12.1480, 12.7631, 12.449

In [22]:
e = torch.sum(d)

In [23]:
e

tensor(3444.5505, grad_fn=<SumBackward0>)

In [24]:
e.backward()

In [25]:
print(e)

tensor(3444.5505, grad_fn=<SumBackward0>)


In [26]:
torch.mean(torch.tensor([10., 10., 13., 10., 34., 45., 65., 67., 87., 89., 87., 34.]))

tensor(45.9167)

In [27]:
torch.mean(torch.Tensor([10, 10, 13, 10, 34, 45, 65, 67, 87, 89, 87, 34]))

tensor(45.9167)

In [28]:
d = torch.Tensor([1, 2, 3, 5, 4, 2, 3, 5, 67, 34, 5, 6]).view(4, 3)

In [29]:
d

tensor([[ 1.,  2.,  3.],
        [ 5.,  4.,  2.],
        [ 3.,  5., 67.],
        [34.,  5.,  6.]])

In [30]:
torch.mean(d)

tensor(11.4167)

In [31]:
torch.mean(d, dim = 0)

tensor([10.7500,  4.0000, 19.5000])

In [32]:
torch.mean(d, dim = 1)

tensor([ 2.0000,  3.6667, 25.0000, 15.0000])

In [33]:
torch.median(d)

tensor(4.)

In [34]:
torch.median(d, dim = 0)

torch.return_types.median(
values=tensor([3., 4., 3.]),
indices=tensor([2, 1, 0]))

In [35]:
torch.median(d, dim = 1)

torch.return_types.median(
values=tensor([2., 4., 5., 6.]),
indices=tensor([1, 1, 1, 2]))

In [36]:
torch.mode(d)

torch.return_types.mode(
values=tensor([1., 2., 3., 5.]),
indices=tensor([0, 2, 0, 1]))

In [37]:
torch.mode(d, dim = 0)

torch.return_types.mode(
values=tensor([1., 5., 2.]),
indices=tensor([0, 3, 1]))

In [38]:
torch.mode(d, dim = 1)

torch.return_types.mode(
values=tensor([1., 2., 3., 5.]),
indices=tensor([0, 2, 0, 1]))

In [39]:
torch.std(d)

tensor(19.6212)

In [40]:
torch.std(d, dim = 0)

tensor([15.5858,  1.4142, 31.7122])

In [41]:
torch.std(d, dim = 1)

tensor([ 1.0000,  1.5275, 36.3868, 16.4621])

In [42]:
torch.var(d)

tensor(384.9924)

In [43]:
torch.var(d, dim = 0)

tensor([ 242.9167,    2.0000, 1005.6667])

In [44]:
torch.var(d, dim = 1)

tensor([1.0000e+00, 2.3333e+00, 1.3240e+03, 2.7100e+02])

In [45]:
def forward(x):
    return x * w    

In [46]:
def loss(x, y):
    y_pred = forward(x)
    return (y_pred - y) ** 2

In [47]:
x_data = [11.0, 22.0, 33.0]

In [48]:
y_data = [21.0, 14.0, 64.0]

In [49]:
w = Variable(torch.Tensor([1.0]), requires_grad = True)

In [50]:
print("predict before training: ", 4, forward(4).data[0])

predict before training:  4 tensor(4.)


In [51]:
for epoch in range(10):
    for x_val, y_val in zip(x_data, y_data):
        los = loss(x_val, y_val)
        los.backward()
        print("\tgrad: ", x_val, y_val, w.grad.data[0])
        w.data = w.data - 0.01 * w.grad.data
        
        w.grad.data.zero_()
    print('process: ', epoch, los.data[0])   

print('predict after training: ', 4, forward(4).data[0])

	grad:  11.0 21.0 tensor(-220.)
	grad:  22.0 14.0 tensor(2481.6001)
	grad:  33.0 64.0 tensor(-51303.6484)
process:  0 tensor(604238.8125)
	grad:  11.0 21.0 tensor(118461.7578)
	grad:  22.0 14.0 tensor(-671630.6875)
	grad:  33.0 64.0 tensor(13114108.)
process:  1 tensor(3.9481e+10)
	grad:  11.0 21.0 tensor(-30279010.)
	grad:  22.0 14.0 tensor(1.7199e+08)
	grad:  33.0 64.0 tensor(-3.3589e+09)
process:  2 tensor(2.5900e+15)
	grad:  11.0 21.0 tensor(7.7553e+09)
	grad:  22.0 14.0 tensor(-4.4050e+10)
	grad:  33.0 64.0 tensor(8.6030e+11)
process:  3 tensor(1.6991e+20)
	grad:  11.0 21.0 tensor(-1.9863e+12)
	grad:  22.0 14.0 tensor(1.1282e+13)
	grad:  33.0 64.0 tensor(-2.2034e+14)
process:  4 tensor(1.1146e+25)
	grad:  11.0 21.0 tensor(5.0875e+14)
	grad:  22.0 14.0 tensor(-2.8897e+15)
	grad:  33.0 64.0 tensor(5.6436e+16)
process:  5 tensor(7.3118e+29)
	grad:  11.0 21.0 tensor(-1.3030e+17)
	grad:  22.0 14.0 tensor(7.4013e+17)
	grad:  33.0 64.0 tensor(-1.4455e+19)
process:  6 tensor(4.7966e+34)
	

In [54]:
from torch import FloatTensor
from torch.autograd import Variable

In [55]:
a = Variable(FloatTensor([5]))

In [57]:
weights = [Variable(FloatTensor([i]), requires_grad = True) for i in (12, 53, 91, 123)]

In [58]:
w1, w2, w3, w4 = weights

In [59]:
b = w1 * a
c = w2 * a
d = w3 * b + w4 * c

Loss = (10 -d)
Loss.backward()

for index, weight in enumerate(weights, start = 1):
    gradient, *_ = weight.grad.data
    print(f"Gradient of w{index} w.r.t. Loss is: {gradient}")    

Gradient of w1 w.r.t. Loss is: -455.0
Gradient of w2 w.r.t. Loss is: -615.0
Gradient of w3 w.r.t. Loss is: -60.0
Gradient of w4 w.r.t. Loss is: -265.0


In [60]:
x = Variable(torch.Tensor(4, 4).uniform_(-4, 5))
y = Variable(torch.Tensor(4, 4).uniform_(-3, 2))

In [61]:
x

tensor([[-1.1282,  4.0778,  2.1476,  0.8352],
        [-3.9400,  2.3189,  4.7109,  0.4280],
        [ 3.5597, -0.9519, -3.7196,  0.3876],
        [ 2.2939, -1.4769,  0.7608,  1.2525]])

In [62]:
y

tensor([[ 1.8995, -1.8042, -2.6720, -1.6643],
        [ 1.3016, -1.6604, -0.6640, -2.2976],
        [-1.7871, -2.6455,  0.2479,  1.1873],
        [-0.8329, -0.6812,  0.1410, -0.8680]])

In [63]:
z = torch.mm(x, y)

In [64]:
z

tensor([[ -1.3687, -10.9857,   0.9569,  -5.6669],
        [-13.2409,  -9.4961,  10.2161,   6.4508],
        [ 11.8471,   4.7342,  -9.7470,  -8.4899],
        [  0.0321,  -4.5521,  -4.7835,  -0.6082]])

In [65]:
z = Variable(torch.Tensor(4, 4).uniform_(-5, 5))
z

tensor([[ 0.4200,  2.0541,  3.8482,  2.5524],
        [ 1.2238,  4.2838, -4.4571, -3.2921],
        [ 4.0647,  4.6486, -2.3308,  3.9258],
        [-0.5736, -1.3971, -0.1930, -1.2998]])

In [66]:
print('Requires Gradient: ', z.requires_grad)

Requires Gradient:  False


In [72]:
print('Volatile: ',  (z.volatile))

Volatile:  False


D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: volatile was removed (Variable.volatile is always False)
  """Entry point for launching an IPython kernel.


In [73]:
print('Gradients: ', z.grad)

Gradients:  None


In [74]:
z.data

tensor([[ 0.4200,  2.0541,  3.8482,  2.5524],
        [ 1.2238,  4.2838, -4.4571, -3.2921],
        [ 4.0647,  4.6486, -2.3308,  3.9258],
        [-0.5736, -1.3971, -0.1930, -1.2998]])

In [76]:
mat1 = torch.FloatTensor(4, 4).uniform_(0, 1)
mat1

tensor([[0.0220, 0.0298, 0.6245, 0.6771],
        [0.2102, 0.6800, 0.5864, 0.2874],
        [0.9668, 0.8840, 0.9142, 0.3369],
        [0.5030, 0.2619, 0.9092, 0.9542]])

In [77]:
mat2 = torch.FloatTensor(5, 4).uniform_(0, 1)

In [78]:
mat2

tensor([[0.2520, 0.6453, 0.9247, 0.5636],
        [0.3317, 0.4235, 0.1720, 0.9896],
        [0.2494, 0.6093, 0.0623, 0.5482],
        [0.8529, 0.0889, 0.6774, 0.5103],
        [0.7707, 0.2648, 0.2008, 0.2764]])

In [79]:
mat1 + 10.

tensor([[10.0220, 10.0298, 10.6245, 10.6771],
        [10.2102, 10.6800, 10.5864, 10.2874],
        [10.9668, 10.8840, 10.9142, 10.3369],
        [10.5030, 10.2619, 10.9092, 10.9542]])

In [80]:
mat2 - 1

tensor([[-0.7480, -0.3547, -0.0753, -0.4364],
        [-0.6683, -0.5765, -0.8280, -0.0104],
        [-0.7506, -0.3907, -0.9377, -0.4518],
        [-0.1471, -0.9111, -0.3226, -0.4897],
        [-0.2293, -0.7352, -0.7992, -0.7236]])

In [81]:
vec1 = torch.FloatTensor(4).uniform_(0, 1)

In [82]:
vec1

tensor([0.4273, 0.9212, 0.4693, 0.1331])

In [83]:
mat1

tensor([[0.0220, 0.0298, 0.6245, 0.6771],
        [0.2102, 0.6800, 0.5864, 0.2874],
        [0.9668, 0.8840, 0.9142, 0.3369],
        [0.5030, 0.2619, 0.9092, 0.9542]])

In [84]:
mat1 + vec1

tensor([[0.4493, 0.9510, 1.0938, 0.8102],
        [0.6375, 1.6012, 1.0557, 0.4205],
        [1.3941, 1.8052, 1.3835, 0.4700],
        [0.9303, 1.1831, 1.3785, 1.0873]])

In [86]:
mat1 * mat1

tensor([[4.8245e-04, 8.8623e-04, 3.8997e-01, 4.5851e-01],
        [4.4191e-02, 4.6240e-01, 3.4385e-01, 8.2593e-02],
        [9.3473e-01, 7.8147e-01, 8.3575e-01, 1.1353e-01],
        [2.5298e-01, 6.8598e-02, 8.2665e-01, 9.1052e-01]])

In [95]:
mat2_t = mat2.t()

In [96]:
mat2_t

tensor([[0.2520, 0.3317, 0.2494, 0.8529, 0.7707],
        [0.6453, 0.4235, 0.6093, 0.0889, 0.2648],
        [0.9247, 0.1720, 0.0623, 0.6774, 0.2008],
        [0.5636, 0.9896, 0.5482, 0.5103, 0.2764]])

In [99]:
torch.matmul(mat1, mat2_t)

tensor([[0.9838, 0.7974, 0.4337, 0.7900, 0.3373],
        [1.1960, 0.7430, 0.6608, 0.7837, 0.5392],
        [1.8494, 1.1858, 1.0214, 1.6945, 1.2559],
        [1.6744, 1.3785, 0.8647, 1.5552, 0.9033]])

In [100]:
from torch.distributions.bernoulli import Bernoulli

In [101]:
dist = Bernoulli(torch.tensor([0.3, 0.6, 0.9]))

In [102]:
dist

Bernoulli(probs: torch.Size([3]))

In [103]:
dist.sample()

tensor([1., 1., 1.])

In [104]:
from torch.distributions.beta import Beta

In [105]:
dist = Beta(torch.tensor([0.5]), torch.tensor([0.5]))

In [106]:
dist

Beta()

In [107]:
dist.sample()

tensor([0.1756])

In [108]:
from torch.distributions.binomial import Binomial

In [109]:
dist = Binomial(100, torch.tensor([0, .2, .8, 1]))

In [110]:
dist

Binomial(total_count: torch.Size([4]), probs: torch.Size([4]), logits: torch.Size([4]))

In [111]:
dist.sample()

tensor([  0.,  25.,  83., 100.])

In [112]:
from torch.distributions.categorical import Categorical

In [113]:
dist = Categorical(torch.tensor([0.2, .2, .2, .2, .2]))

In [114]:
dist

Categorical(probs: torch.Size([5]))

In [118]:
dist.sample()

tensor(4)

In [120]:
from torch.distributions.laplace import Laplace

In [122]:
dist = Laplace(torch.tensor([10.0]), torch.tensor([0.99]))

In [123]:
dist

Laplace(loc: tensor([10.]), scale: tensor([0.9900]))

In [124]:
dist.sample()

tensor([11.4690])

In [125]:
from torch.distributions.normal import Normal

In [138]:
dist = Normal(torch.tensor([0.0]), torch.tensor([1.]))

In [139]:
dist

Normal(loc: tensor([0.]), scale: tensor([1.]))

In [140]:
dist.sample()

tensor([-1.6848])